spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      default:
        contentType: application/json

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

topics:
  user-created-request: user.created.request
  user-created-success: user.created.success
  registration-complete: user.registration.complete
  delete-user-account-complete: delete.user.complete
  appointment-booked-complete: appointment.booked.complete
  appointment-status-changed: appointment.status.changed
