server:
  port: 9001

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: ${DB_USER:auth_user}
    password: ${DB_PASSWORD:changeme}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    stream:
      bindings:
        createUser-out-0:
          destination: ${topics.user-created-request}
          group: ${spring.application.name}
