server:
  port: 9003

frontend:
  base:
    url: http://frontend:5174

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    stream:
      bindings:
        handleRegistrationEvent-in-0:
          destination: ${topics.registration-complete}
          group: ${spring.application.name}
        handleUserDeleted-in-0:
          destination: ${topics.delete-user-account-complete}
          group: ${spring.application.name}
        handleAppointmentBooked-in-0:
          destination: ${topics.appointment-booked-complete}
          group: ${spring.application.name}
        handleAppointmentStatusChanged-in-0:
          destination: ${topics.appointment-status-changed}
          group: ${spring.application.name}
